# Generated by Django 5.2 on 2025-05-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clug',
            new_name='slug',
        ),
    ]
